---

# Standalone example for ddns

version: "3.9"

services:
  ddns:
    image: plaenkler/ddns
    container_name: ddns
    restart: always
    networks:
      - web
    ports:
      - 80:80
    volumes:
      - ./ddns:/app/data

networks:
  web:
    external: false