---

# Local build

version: '3.9'

services:
  ddns:
    image: ddns
    container_name: ddns
    restart: always
    networks:
      - web
    ports:
      - 80:80
    volumes:
      - ./ddns:/app/data

networks:
  web:
    external: false